
import matplotlib.pyplot as plt
import numpy as np

# function for reading input filer
# returns all lines from the file
def read_file(file_name):
    with open(file_name, "r") as f:
        lines = f.readlines()
    return lines

# convert a list of strings into a list of floating point numbers
def convert_to_float(sx):
    x=[]
    for s in sx:
        x.append(float(s))
    return x    

print("Bars for pds avg of ZINC15 A-K+\n")

# read histogram data generated by get_all_pds_avg_to_one_dat_file.sh
fin="get_all_pds_avg_to_one_dat_file.dat"
lines=read_file(fin)
print("input read\n")

# first row contains avg_pds intervals
sx=lines[0].split(";")[1:-1]
x0=convert_to_float(sx)
x=np.array(x0)

# remaining rows contain histogram values for ZINC15 bins A-K
labels=[]
heights=[]
abcd=""
for line in lines[1:]:
    sline=line.split(";")[1:-1]
    label=line.split(";")[0]
    print(label,sline)
    labels.append(label)
    hline=convert_to_float(sline)
    heights.append(hline)


# 3a; settings for bar plot
plt.figure(figsize=(5.5, 5.5))
#                A,             B,        C,       D,          E,             F,                 G,         H,               I,        J,          K  
color_style=["coral", "dodgerblue","darkgrey","orange","olivedrab","palevioletred","mediumslateblue","goldenrod","mediumseagreen","salmon","cornflowerblue"]
w=0.14

# SELECT which molecular weight bins will be plotted
# the input file contains bins A-K
# Uncomment ONLY ONE of the following options

# A-F:
for i in range(0,6):
    j=i

# G-K:
#for i in range(6,11):
#    j=i-6
    
    h=heights[i]
    # for G-K bins: shift = 0.25
    # for A-F bins: shift = 0.15
    wx=w*j+0.15 
    # add selected bin to the output file name
    abcd+=labels[i]

    # calculate total number of structures in each letter
    total = int(sum(h))
    plt.bar(x+wx,h,width=w,label=f"{labels[i]} ({total:,})",color=color_style[i],log=True)

# output file name based on plotted bins
nameP="histogram_pds_avg_AK_united_"+abcd

png_name=str(nameP)+"_bar.png"
eps_name=str(nameP)+"_bar.eps"

plt.legend()

# define logarithmic Y-axis ticks
ticks_y=[
1,2,3,4,5,6,7,8,9,10,
20,30,40,50,60,70,80,90,100,
200,300,400,500,600,700,800,900,1000,
2000,3000,4000,5000,6000,7000,8000,9000,10000,
20000,30000,40000,50000,60000,70000,80000,90000,100000,
200000,300000,400000,500000,600000,700000,800000,900000,1000000,
2000000,3000000,4000000,5000000,6000000,7000000,8000000,9000000,10000000,
20000000,30000000,40000000,50000000,60000000,70000000,80000000,90000000,100000000
]

labels_y=[
"1","","","","","","","","","10$^1$",
"","","","","","","","","10$^2$",
"","","","","","","","","10$^3$",
"","","","","","","","","10$^4$",
"","","","","","","","","10$^5$",
"","","","","","","","","10$^6$",
"","","","","","","","","10$^7$",
"","","","","","","","","10$^8$"
]

plt.xticks(x,fontsize=8)
plt.yticks(ticks=ticks_y,labels=labels_y)

axes = plt.gca()
axes.set_ylim([0.9,2E5])
plt.gca().set(xlabel=r'$\mathrm{PDS_{avg}\ [kcal/mol]}$')

# save histogram in PNG and EPS formats
plt.savefig(png_name, dpi= 300)
plt.savefig(eps_name, format='eps')
plt.close()

exit()
